export const BEFORE_STATE_COMMENT = "BEFORE_STATE_COMMENT" as const;
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS" as const;
export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR" as const;
export const COMMENT_CREATE_SUCCESS = "COMMENT_CREATE_SUCCESS" as const;
export const COMMENT_CREATE_ERROR = "COMMENT_CREATE_ERROR" as const;
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS" as const;
export const COMMENT_DELETE_ERROR = "COMMENT_DELETE_ERROR" as const;
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESS" as const;
export const COMMENT_UPDATE_ERROR = "COMMENT_UPDATE_ERROR" as const;








